export const GET_UNIVERSITIES_REQUEST = "GET_UNIVERSITIES_REQUEST";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAIL = "GET_UNIVERSITIES_FAIL";

export const GET_UNIVERSITY_DETAILS_REQUEST = "GET_UNIVERSITY_DETAILS_REQUEST";
export const GET_UNIVERSITY_DETAILS_SUCCESS = "GET_UNIVERSITY_DETAILS_SUCCESS";
export const GET_UNIVERSITY_DETAILS_FAIL = "GET_UNIVERSITY_DETAILS_FAIL";
export const GET_UNIVERSITY_DETAILS_RESET = "GET_UNIVERSITY_DETAILS_RESET";    




export const ADD_UNIVERSITY = 'ADD_UNIVERSITY';
export const UNIVERSITY_FAILED = 'UNIVERSITY_FAILED';


export const MODIFY_UNIVERSITY = 'MODIFY_UNIVERSITY';
export const MODIFY_UNIVERSITY_FAILED = 'MODIFY_UNIVERSITY_FAILED';

export const DELETE_UNIVERSITY = 'DELETE_UNIVERSITY';
export const DELETE_UNIVERSITY_FAILED = 'DELETE_UNIVERSITY_FAILED';