export const GET_UNIVERSITIES_REQUEST = "GET_UNIVERSITIES_REQUEST";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAIL = "GET_UNIVERSITIES_FAIL";

export const GET_UNIVERSITY_DETAILS_REQUEST = "GET_UNIVERSITY_DETAILS_REQUEST";
export const GET_UNIVERSITY_DETAILS_SUCCESS = "GET_UNIVERSITY_DETAILS_SUCCESS";
export const GET_UNIVERSITY_DETAILS_FAIL = "GET_UNIVERSITY_DETAILS_FAIL";
export const GET_UNIVERSITY_DETAILS_RESET = "GET_UNIVERSITY_DETAILS_RESET";    